def get_default_ylims():
    ylims_pyr = {
        "dvdt_rising": [0, 800],
        "dvdt_falling": [0, 800],
        "AP_HW": [0, 1000],
        "AP_thr_V": [-75, 0],
        "AHP_depth_V": [None, None],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1500],
        "maxHillSlope": [0, 5000],
        "I_maxHillSlope": [0, 1.0],
        "FIMax_1": [0, 800],
        "FIMax_4": [0, 800],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 250],
    }
    ylims_tv = {
        "dvdt_rising": [0, 800],
        "dvdt_falling": [0, 800],
        "AP_HW": [0, 1000],
        "AHP_depth_V": [None, None],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1500],
        "maxHillSlope": [0, None],
        "I_maxHillSlope": [0, 0.5],
        "FIMax_1": [0, 800],
        "FIMax_4": [0, 800],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 400],
    }
    ylims_cw = {
        "dvdt_rising": [0, 800],
        "dvdt_falling": [0, 800],
        "AP_HW": [0, 1000],
        "AHP_depth_V": [None, None],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 8],
        "FISlope": [0, 250],
        "maxHillSlope": [0, 5000],
        "I_maxHillSlope": [0, 0.5],
        "FIMax_1": [0, 800],
        "FIMax_4": [0, 800],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 200],
    }

    ylims_giant = {
        "dvdt_rising": [0, 800],
        "dvdt_falling": [0, 800],
        "AP_HW": [0, 1000],
        "AHP_depth_V": [-75, -40],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1000],
        "maxHillSlope": [0, 1000],
        "I_maxHillSlope": [0, 1.0],
        "FIMax_1": [0, 800],
        "FIMax_4": [0, 800],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 400],
    }
    ylims_giant_maybe = {
        "dvdt_rising": [0, 800],
        "dvdt_falling": [0, 800],
        "AP_HW": [0, 1000],
        "AHP_depth_V": [-75, -40],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1000],
        "maxHillSlope": [0, 1000],
        "I_maxHillSlope": [0, 1.0],
        "FIMax_1": [0, 800],
        "FIMax_4": [0, 800],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 400],
    }

    ylims_bushy = {
        "dvdt_rising": [0, 200],
        "dvdt_falling": [0, 200],
        "AP_HW": [0, 3.0],
        "AHP_depth_V": [-75, -40],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1000],
        "maxHillSlope": [0, 1000],
        "I_maxHillSlope": [0, 1.0],
        "FIMax_1": [0, None],
        "FIMax_4": [0, None],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 400],
    }

    ylims_tstellate = {
        "dvdt_rising": [0, 400],
        "dvdt_falling": [0, 400],
        "AP_HW": [0, 3.0],
        "AHP_depth_V": [-75, -40],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1000],
        "maxHillSlope": [0, 1000],
        "I_maxHillSlope": [0, 1.0],
        "FIMax_1": [0, None],
        "FIMax_4": [0, None],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 400],
    }

    ylims_dstellate = {
        "dvdt_rising": [0, 400],
        "dvdt_falling": [0, 400],
        "AP_HW": [0, 3.0],
        "AHP_depth_V": [-75, -40],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1000],
        "maxHillSlope": [0, 1000],
        "I_maxHillSlope": [0, 1.0],
        "FIMax_1": [0, None],
        "FIMax_4": [0, None],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 400],
    }

    ylims_octopus = {
        "dvdt_rising": [0, 200],
        "dvdt_falling": [0, 200],
        "AP_HW": [0, 3.0],
        "AHP_depth_V": [-75, -40],
        "AP_thr_V": [-75, 0],
        "AdaptRatio": [0, 2],
        "FISlope": [0, 1000],
        "maxHillSlope": [0, 1000],
        "I_maxHillSlope": [0, 1.0],
        "FIMax_1": [0, None],
        "FIMax_4": [0, None],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, 400],
    }
    ylims_default = {
        "dvdt_rising": [0, 1000],
        "dvdt_falling": [0, 1000],
        "AP_HW": [0, 2000],
        "AP_thr_V": [-75, 0],
        "AHP_depth_V": [-85, -40],
        "AdaptRatio": [0, 5],
        "FISlope": [0, 1500],
        "maxHillSlope": [0, None],
        "I_maxHillSlope": [0, 1000],
        "FIMax_1": [0, 800],
        "FIMax_4": [0, 800],
        "taum": [0, None],
        "taum_averaged": [0, None],
        "RMP": [-80, -40],
        "Rin": [0, None],
    }

    ylims = {
        "pyramidal": ylims_pyr,
        "tuberculoventral": ylims_tv,
        "cartwheel": ylims_cw,
        "giant": ylims_giant,
        "giant_maybe": ylims_giant_maybe,
        "bushy": ylims_bushy,
        "t-stellate": ylims_tstellate,
        "d-stellate": ylims_dstellate,
        "octopus": ylims_octopus,
        "default": ylims_default,  # a default set when "default" is specified in the configuration
    }
    return ylims
